---
name: Polish the code

on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"

  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - "notest/**"

  schedule:
    # Run the workflow at 6:30 AM UTC on the 18th of every month
    - cron: "30 6 18 * *"
    # Scheduled runs do not commit-changes automatically to the same branch

permissions:
  # only prettier-fix and phpcs-phpcbf need write permission, for others read is enough
  contents: read

jobs:
  prettier-fix:
    # Note: runs-on doesn't accept all expressions, so a string is used
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    # Limit the running time
    timeout-minutes: 10
    steps:
      - name: Invoke the Prettier fix
        uses: WorkOfStan/prettier-fix@v1.1.4
        with:
          commit-changes: ${{ github.event_name != 'schedule' }}

  super-linter:
    needs: prettier-fix
    uses: WorkOfStan/seablast-actions/.github/workflows/linter.yml@v0.2.3
    with:
      runs-on: "ubuntu-latest"
